services:
  floci:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4566"
      # - "6379-6399:6379-6399"
      # - "7001-7099:7001-7099"
    volumes:
      - ${USERPROFILE}\data-floci:/app/data 
      - //var/run/docker.sock:/var/run/docker.sock #this seems to work on Windows
      - ./scripts:/etc/floci/init/start.d
      - ./scripts:/etc/floci/init/stop.d
    environment:
      FLOCI_SERVICES_DOCKER_NETWORK: floci_default
      FLOCI_SERVICES_RDS_PROXY_BASE_PORT: "7001"
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_BASE_URL: floci
      #QUARKUS_LOG_LEVEL: DEBUG
      #QUARKUS_HTTP_ACCESS_LOG_ENABLED: true
    networks:
        localaws:
          aliases:
            - localhost.floci.cloud

networks:
  localaws:
    name: localaws


